### ISSUE TITLE
No columns to parse from file

### ISSUE THREAD

**Issue by shainaraza** [bernaljg/covid19-classification#12]
Any thoughts why am I getting this error while running litcovid_dataset_from_xml.py 

```
Average Length of full text: 1769.096193689694
Traceback (most recent call last):
  File "/content/drive/MyDrive/LitCOVID/covid19-classification-master/scripts/litcovid_dataset_from_xml.py", line 44, in <module>
    litcovid = load_all_litcovid()
  File "/content/drive/MyDrive/LitCOVID/covid19-classification-master/scripts/utils.py", line 68, in load_all_litcovid
    df = pd.read_csv(file,sep='\t',comment='#', header=None)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by bernaljg** [comment]
when you run this line "wget -O litcovid_source_general.tsv https://www.ncbi.nlm.nih.gov/research/coronavirus-api/export/tsv?filters=%7B%22topics%22%3A%5B%22General%20Info%22%5D%7D" are you getting a tsv file saved to your directory? I think this error might be due to an empty tsv file.

**Comment by shainaraza** [comment]
this resolved my issue , thanks @bernaljg
