### ISSUE TITLE
title not found

### ISSUE THREAD

**Issue by shainaraza** [bernaljg/covid19-classification#14]
I installed data packages from litcovd.sh file and get all those source files in tsv format and then i run the file on a subset of xml file and this error I get : any idea what am I doing wrong

```

%cd ../scripts
!python litcovid_dataset_from_xml.py

```
```
/content/drive/My Drive/LitCOVID/covid19-classification-master/scripts
Average Length of full text: 1773.9923504452279
Traceback (most recent call last):
  File "litcovid_dataset_from_xml.py", line 50, in <module>
    litcovid_dataset['title_len'] = [len(str(t).split()) for t in litcovid_dataset.title]
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'title'
```

**Comment by shainaraza** [comment]
the format of litcovid is

![image](https://user-images.githubusercontent.com/32249936/144600871-2fffbc97-cba9-4e07-89a8-758e00e7a9ff.png)

**Comment by shainaraza** [comment]
I believe this line
`litcovid_dataset['title_len'] = [len(str(t).split()) for t in litcovid_dataset.title_e]
`
should be 

`litcovid_dataset['title_len'] = [len(str(t).split()) for t in litcovid_dataset.title_e]
`as per new files title_e column

**Comment by shainaraza** [comment]
this is resolved, just need to change title to title_e inside litcovid_dataset_from_xml.py
